[package]
name = "net_ensembles"
version = "0.1.0"
authors = ["Yannick Feld"]
edition = "2018"
readme = "README.md"
description = "Erdős-Rényi and small world ensembles. For simple sampling or Monte Carlo simulations"
repository = "https://github.com/Pardoxa/net_ensembles"
keywords = [
  "small-world",
  "Erdős-Rènyi",
  "Erdoes-Renyi",
  "random graph ensemble"
  ]
categories = ["science"]
documentation = "https://pardoxa.github.io/net_ensembles/v0.1.0/doc/net_ensembles/"
license = "MIT OR Apache-2.0"
homepage = "https://www.yfeld.de/Library.html"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"

[dev-dependencies]
rand_pcg = "*"
