name: Rust unit tests - master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run serde_support tests
      run: cargo test --verbose
    - name: Run tests
      run: cargo test --verbose --no-default-features
